name: Dotnet Test
run-name: Dotnet Test
on: pull_request_target

jobs:
  version-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10'

    - id: run_hello_world
      run: |
        output=( $(dotnet run HelloWorld.cs))
        echo "HELLO_WORLD=$output" >> "$GITHUB_OUTPUT"

    - name: Comment if version not updated
      uses: hasura/comment-progress@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        number: ${{ github.event.number }}
        id: hello-world
        message: ${{ steps.run_hello_world.outputs.HELLO_WORLD }}
        recreate: true
